### ISSUE TITLE
server not handling null values correctly - dglogik.jar

### ISSUE THREAD

**Issue by jdsdc** [IOT-DSA/dslink-dart-dgapi#17]
Server sends null pointer exception which results in other links subscribing to values from dgApi not getting updated values. The used dglogik.jar version is **1.3.0**. Niagara 4.9

```
[2022-01-24 08:51:10.936282] [WARNING][DSA] Error subscribing to slot:/System/LB01/FF001$2dFO001_MAN/SS_Log: java.lang.NullPointerException
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.ApiBundle.get(ApiBundle.java:143)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.ApiBundle.getValue(ApiBundle.java:250)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.json.JsonApiConnection.encodeValue(JsonApiConnection.java:561)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.json.JsonApiConnection.encodeSubscription(JsonApiConnection.java:420)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.json.JsonApiConnection.sendResult(JsonApiConnection.java:238)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.ApiEngine.service(ApiEngine.java:84)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.json.BDGJsonApiServlet.process(BDGJsonApiServlet.java:179)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.dglogik.dglux.api.json.BDGJsonApiServlet.service(BDGJsonApiServlet.java:207)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at javax.baja.web.BWebServlet.doService(BWebServlet.java:196)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at javax.baja.web.BWebServlet.access$000(BWebServlet.java:34)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at javax.baja.web.BWebServlet$Servlet.doPost(BWebServlet.java:336)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1780)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.tridium.web.filters.ContextFilter.doFilter(ContextFilter.java:42)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.tridium.web.filters.LocaleFilter.doFilter(LocaleFilter.java:31)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.tridium.web.filters.TridiumSecurityFilter.doFilter(TridiumSecurityFilter.java:62)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.tridium.web.filters.AddSubjectFilter.lambda$null$0(AddSubjectFilter.java:56)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at java.security.AccessController.doPrivileged(Native Method)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.tridium.web.filters.AddSubjectFilter.lambda$doFilter$1(AddSubjectFilter.java:55)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at java.security.AccessController.doPrivileged(Native Method)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.tridium.web.filters.AddSubjectFilter.doFilter(AddSubjectFilter.java:53)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at com.tridium.jetty.DisallowTraceHandler.handle(DisallowTraceHandler.java:43)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.Server.handle(Server.java:539)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[2022-01-24 08:51:10.936282] [WARNING][DSA] 	at java.lang.Thread.run(Thread.java:748)
```

@rinick , @a-hansen

**Comment by a-hansen** [comment]
This is a problem on the Niagara side, dealing with it out-of-band.
